title: ksuke

theme: jekyll-theme-cayman
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

# The font used for headings. Expects a string that is a valid CSS font-family value.
font_heading: "'Roboto Slab', Helvetica, Arial, sans-serif"

# The text font. Expects a string that is a valid CSS font-family value.
font: "'Noto Sans', Helvetica, Arial, sans-serif"

# The string encoding what fonts to fetch from Google Fonts.
# See: https://qwtel.com/hydejack/docs/configuration/
google_fonts: Roboto+Slab:700|Noto+Sans:400,400i,700,700i

plugins:
 - jekyll-sitemap
 
 
